[package]
name = "symetrical_grid"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/delta1024/grid"
description = "A library for dealing with 2D data structures"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
